# Kling Video Effects Configuration
# Applies premade video effects to images using the Kling API

output_directory: /Users/ethanhsu/Desktop/GAI/Report
testbed: http://192.168.31.40:8000/kling/
template_path: templates/I2V templates.pptx

# Global settings (can be overridden per task)
duration: 5

output:
  directory: /Users/ethanhsu/Desktop/GAI/Report
  group_tasks_by: 3

schedule:
  start_time: ''
  comment: 'Time format: HH:MM (24-hour format). Leave empty to start immediately'

base_folder: ../Media Files/Kling Effects/1208 3 Styles

design_link: https://docs.google.com/spreadsheets/d/18pNGtPzinObrhQt4aiLkyCRLTULZwQDHk7wlobe8FKI/edit?gid=46494616#gid=46494616
source_video_link: https://cyberlinkcorp-my.sharepoint.com/:f:/g/personal/onedrive_qa1_cyberlink_com/IgCXY8-VCzXWRKYu5965SojQASycGk8yE3QW7RS12HPc5NU?e=1d75my

# Tasks - each represents a style/effect to apply
# Effect selection per task:
# - Use 'effect' to select from preset effects (see effect_options below)
# - Use 'custom_effect' to specify a custom effect name (has priority over 'effect')
# The effect name (custom_effect or effect) is used as the subfolder name in base_folder
tasks:
  - effect: 
    custom_effect: 'scarlet_and_snow' 

  - effect:
    custom_effect: 'magic_cloak'

  - effect: 
    custom_effect: 'spark_in_the_snow'

comments:
  base_folder: >
    Root folder containing effect subfolders. Each effect folder should have 
    'Source', 'Generated_Video', and 'Metadata' subfolders.
    Folder names should match the effect or custom_effect name.
  effect: >
    Preset effect from the available options. Used as folder name if custom_effect is empty.
  custom_effect: >
    Custom effect name that takes priority over the preset 'effect' option.
    Also used as the folder name when specified.
  output_group_tasks_by: >
    Set to 0 (or omit) to create individual reports per task. 
    Set to N to group N tasks into one combined report.

# Available preset effects (use with 'effect' field):
effect_options:
  - 3d_cartoon_1
  - 3d_cartoon_2
  - a_list_look
  - american_comics
  - angel_wing
  - anime_figure
  - baseball
  - bloombloom
  - boss_coming
  - boyfriend
  - brown_bear_hug
  - building_collapse
  - car_explosion
  - c4d_cartoon
  - celebration
  - construction_worker
  - cry_cry
  - cute_ghost_transform
  - cute_pumpkin_transform
  - dark_wing
  - day_to_night
  - demon_transform
  - disappear
  - dishwasher
  - dizzydizzy
  - dollar_rain
  - double_gun
  - eagle_snatch
  - emoji
  - expansion
  - fairy_wing
  - feed_mooncake
  - felt_felt
  - firework
  - fly_fly
  - flyer
  - fuzzyfuzzy
  - gallery_ring
  - girlfriend
  - guess_what
  - gun_shot
  - guardian_spirit
  - halloween_escape
  - heart_gesture_1
  - hug_from_past
  - inner_voice
  - instant_film
  - instant_kid
  - japanese_anime_1
  - jazz_jazz
  - jelly_jiggle
  - jelly_press
  - jelly_slice
  - jelly_squish
  - jesus_hug
  - jumpdrop
  - knock_knock_halloween
  - let's_ride
  - lightning_power
  - lie_flat
  - long_hair
  - luminous_elf
  - magic_broom
  - magic_fireball
  - marry_me
  - media_interview
  - memory_alive
  - mushroom
  - muscle_pet
  - mythic_style
  - mummy_transform
  - office_escape_plow
  - pet_bee
  - pet_chef
  - pet_chinese_opera
  - pet_delivery
  - pet_dance
  - pet_lion
  - pet_moto_rider
  - pet_warrior
  - pet_wizard
  - pixelpixel
  - piggy_morph
  - plushcut
  - polar_bear_hug
  - pucker_up
  - pumpkin_head_transform
  - rampage_ape
  - rocketrocket
  - running_man
  - santa_gifts
  - santa_hug
  - shark_alert
  - siblings
  - ski_ski
  - skateskate
  - smoke_smoke
  - snowboarding
  - snatched
  - splashsplash
  - squish
  - squeeze_scream
  - steampunk
  - surfsurf
  - swing_swing
  - swish_swish
  - tiger_hug
  - thumbs_up
  - trampoline
  - trampoline_night
  - vampire_transform
  - watermelon_bomb
  - wig_out
  - witch_transform
  - wool_curly
  - woodland_elf
  - yearbook
  - zombie_transform
