template_path: templates/I2V templates.pptx
comparison_template_path: templates/I2V Comparison Template.pptx
output_directory: /Users/ethanhsu/Desktop/GAI/Report
comment_output_directory: 'Optional: Global output directory for all generated PPTX files. Can be overridden per task. Default
  is current directory.'
testbed: http://192.168.31.40:8000/kling/
model_version: v2.5-turbo
comment_model_version: 'Model version to use for video generation. Options: ''v1.6'', ''v2.1''. Default is ''v2.1'' if not
  specified.'
schedule:
  start_time: ''
  comment: 'Time format: HH:MM (24-hour format). Leave empty to start immediately'
group_tasks_by: 4

tasks:
- mode: std
  folder: ../Media Files/Kling 2.5/1127 Party V4 Debug
  prompt: |
    4:3 mid-shot, head-to-thigh framing, fixed stable camera with ultra-slow smooth orbit while gently pulling back, luxury indoor studio with cool white soft lighting, deep red velvet curtain and stacked red gift boxes background, dark glossy reflective floor with sparse high-gloss mirror-foil silver confetti squares (1â€“2 cm) creating vivid cold-white reflections and champagne highlights only on the floor layer, elegant woman standing centered taking a few graceful steps left then naturally stopping, relaxed posture, smooth movement in sync with camera orbit, calm confident energy, direct gaze, soft assured smile, right hand firmly holding a clearly visible champagne glass at chest height, instant flash completing the transformation into a pure white sequin mini dress above the knees with a clean-cut hemline and no fabric touching the floor, flash particles only around the dress while the floor confetti stays reflective, cold-white couture tone, bright metallic shimmer, quiet luxury, Dior/Vogue New Year cinematic style.
  negative_prompt: |
    trousers,long gown, evening gown, floor-length dress, ankle-length skirt, train, cloth dragging, translucent dress, see-through fabric, clothing residue, outfit overlap, partial outfit, incomplete outfit, half-changed outfit, broken transformation, interrupted outfit change, fabric blending, glitchy clothing, mixed dress layers, skirt fusion, floating garments, double outfits, duplicate person, blurry transformation, sparkle fog, smoke, glow, distortion, pose mismatch, motion blur, blank expression, cold stare, serious face, extra arms, more than two arms,Bright Sky Blue,old outfit tint,old outfit style,Japanese sailor uniform.
  design_link: https://docs.google.com/presentation/d/1zR01DmJpSFYxI_3x4jWEaaZRqJSw3m1vVbekMPLP9e8/edit?slide=id.g3a979719f3c_2_48#slide=id.g3a979719f3c_2_48
  source_video_link: 
  reference_folder: ''
  use_comparison_template: false
